### ISSUE TITLE
lsmeans of the simplest Bayesian model

### ISSUE THREAD

**Issue by felixthoemmes** [rvlenth/lsmeans#10]
Hello,
One of the most amazing strengths of lsmeans is that it works so seamlessly with lm, lme4, and also with Bayesian methods, such as Rstan / rstanarm. 
I have been using lsmeans with Bayesian models estimated in rstanarm, and it works perfectly, except for one situation that I encountered. 
The simplest possible model, in which we only estimate the mean using a linear model, returns an error. 
Here is a reproducible example:

`#Using the frequentist method works perfectly`
`#all we are doing below is estimate the mean of x using lm`
`x <- rnorm(100,0,1)`
`df1 <- data.frame(x)`
`lm1 <- lm(x~1,data=df1)`
`lsmeans(lm1,"1")`

`#Using rstanarm with the same trivial model (x~1), yields an error`
`library(rstan)`
`library(rstanarm)`
`blm1 <- stan_glm(x~1,data=df1)`
`lsmeans(blm1,"1")`
`as.stanfit(lsmeans(blm1,"1"))`

> Error in validObject(.Object) : 
  invalid class “ref.grid” object: invalid object for slot "post.beta" in class "ref.grid": got class "numeric", should be or extend class "matrix"

With every other model in rstanarm lsmeans works perfectly. E.g., if all I do above is add a single predictor to x, let's say g, then lsmeans will provide the overall mean of x, group means of x within levels of g, etc., when processing the model output from rstanarm.

**Comment by rvlenth** [comment]
I am actually going to deprecate as.stanfit. It is a hack to begin with; and what you can do instead to get the same plots, etc. is to use coda::as.mcmc() and the bayesplot package. If I had realized that earlier, I would never have written as.stanfit.

But please let me know if I am overlooking some important capability from stanfit.

Thanks

Russ

**Comment by felixthoemmes** [comment]
Hi Russ,
Thanks for the quick reply. I used as.mcmc in the past, and the bayesplot package is quite powerful indeed for plotting Bayesian results. 

Let me address two separate points:

1) Even using as.mcmc does not fix this issue. In the Bayesian lm that ONLY includes the intercept, I still get this error. Note that as soon as I have at least one predictor, everything works perfectly fine. And of course the frequentist lm with no predictors (intercept only) ALSO works fine with lsmeans. 

`x <- rnorm(100,0,1)`
`df1 <- data.frame(x)`
`blm1 <- stan_glm(x~1,data=df1)`
`lsmeans(blm1,"1") #does not work`
`as.stanfit(lsmeans(blm1,"1")) #does not work `
`coda::as.mcmc(lsmeans(blm1,"1")) #does not work`

2) It's of course your call to deprecate as.stanfit, but I did find it useful. Unlike as.mcmc, it also reports effective sample size N, and the Rhat statistic. Here is a minimal example. 

`t <- rbinom(100,1,.7)`
`x <- .5*t + rnorm(100,0,1)`
`df3 <- data.frame(t=factor(t),x)`
`blm3 <- stan_glm(x~t,family=gaussian(link = "identity"),data=df3,prior = normal(0,3),`
`prior_intercept = normal(0,3))`
`as.stanfit(lsmeans::lsmeans(blm3,"t",contr="pairwise")$contrasts)`
`summary(as.mcmc(lsmeans(blm3,"t", contr="pairwise")$contrasts))`

> The as.stanfit output looks like:
> Inference for Stan model: continuous.
 > 4 chains, each with iter=1000; warmup=0; thin=1; 
> post-warmup draws per chain=1000, total post-warmup draws=4000.

>               mean se_mean   sd  2.5%   25%   50%   75% 97.5% n_eff Rhat
> contrast_0_-_1 -0.22       0 0.23 -0.66 -0.38 -0.22 -0.06  0.24  4000    1

> Samples were drawn using  at 2017-10-04 21:40:07.
> For each parameter, n_eff is a crude measure of effective sample size,
> and Rhat is the potential scale reduction factor on split chains (at 
> convergence, Rhat=1).


The as.mcmc output like this:

> Iterations = 1:1000
> Thinning interval = 1 
> Number of chains = 4 
> Sample size per chain = 1000 

> 1. Empirical mean and standard deviation for each variable,
>   plus standard error of the mean:

>         Mean             SD       Naive SE Time-series SE 
>     -0.217094       0.233969       0.003699       0.003558 

> 2. Quantiles for each variable:

>    2.5%      25%      50%      75%    97.5% 
> -0.66113 -0.37837 -0.21726 -0.05789  0.23973 

I find the as.stanfit to be more consistent with other output that I expect to see from lsmeans when used for frequentist models, and also like that it is more condensed, and that it lists the parameter at the beginning of the row, which I don't get with as.mcmc.

**Comment by rvlenth** [comment]
Thanks. I will look at this. Also working hard to get **emmeans** up to speed. It will be the continuation of **lsmeans**, and the latter will be retired in due time.

**Comment by felixthoemmes** [comment]
Thanks, Russ. Or maybe just don't bother about it, since emmeans will replace this eventually. I wasn't aware that you are developing emmeans - I am excited to hear this. lsmeans has been one of the most important packages in my teaching (and research), and I am extremely grateful that you wrote it!

**Comment by rvlenth** [comment]
Update. I have fixed the bug you report. It's kind of the "go-to" bug, as I call it -- failure to include `drop = FALSE` when extracting columns from a matrix or data.frame.

So now, `as.mcmc()` at least works (in my current **emmeans** changes, not yet committed to github). I think I will contact the developers of the "stan" family of packages and see if maybe they already offer a method to convert an `mcmc` object to `rstan` or `stanfit`. In a lot of ways, you'd think *they* would want to add that capability so that they can offer all their methods to `mcmc` users.

Russ

**Comment by felixthoemmes** [comment]
Thanks Russ - and great idea to contact the rstan folks directly.

**Comment by rvlenth** [comment]
I think we've resolved this. See the new **emmeans** package for future changes. I'm closing this issue.
