### ISSUE TITLE
Interaction contrasts excluding certain terms

### ISSUE THREAD

**Issue by gavin-kelly-1** [rvlenth/lsmeans#12]
https://github.com/rvlenth/lsmeans/blob/81685280b04cae45e71c9a61204092d9577640a8/R/lsmeans.R#L357

I'm struggling to get the `by` factors excluded, so in a 3-way model, I can get the 2-way interactions per remaining term.  The above line seems to remove the `by` settings, but the subsequent code seems to account for non-null `by`

**Comment by rvlenth** [comment]
How about not worrying about how it's coded, and just try it? Below we obtain two interaction contrasts for two of the factors in a 3-way model, by the third.

```
> library("emmeans") ## but should work in lsmeans too
> noise.lm = lm(noise ~ size * type * side, data = auto.noise)
> lsm = lsmeans(noise.lm, ~ size * type * side)
> contrast(lsm, interaction = "consec", by = "side")
side = L:
 size_consec type_consec   estimate       SE df t.ratio p.value
 M - S       Octel - Std -18.333333 4.409586 24  -4.158  0.0004
 L - M       Octel - Std  30.000000 4.409586 24   6.803  <.0001

side = R:
 size_consec type_consec   estimate       SE df t.ratio p.value
 M - S       Octel - Std -23.333333 4.409586 24  -5.292  <.0001
 L - M       Octel - Std   8.333333 4.409586 24   1.890  0.0709
```

Note I actually did this in the **emmeans** package, but it worked in **lsmeans**. You should switch to **emmeans**, as that's where all new developments are being done, and **lsmeans** will be deprecated.

**Comment by rvlenth** [comment]
Unless you want to ignore one of the factors altogether...

```
> lsm = lsmeans(noise.lm, ~ size * type)  ## excluded side
NOTE: Results may be misleading due to involvement in interactions

> contrast(lsm, interaction = "consec")
 size_consec type_consec  estimate       SE df t.ratio p.value
 M - S       Octel - Std -20.83333 3.118048 24  -6.682  <.0001
 L - M       Octel - Std  19.16667 3.118048 24   6.147  <.0001

Results are averaged over the levels of: side 
```

**Comment by gavin-kelly-1** [comment]
Yes, I'll switch to emmeans, as when I run your example in lsmeans I get
 size_consec type_consec side_consec  estimate       SE df t.ratio p.value
 M - S       Octel - Std R - L        -5.00000 6.236096 24  -0.802  0.4305
 L - M       Octel - Std R - L       -21.66667 6.236096 24  -3.474  0.0020
which is why I "worried" about how the code was written.

**Comment by rvlenth** [comment]
I think you want something more like my second idea

**Comment by rvlenth** [comment]
I guess perhaps there was a bug there, but it's fixed in **emmeans**
