### ISSUE TITLE
Functions to facilitate specifiy equivalence thresholds

### ISSUE THREAD

**Issue by crsh** [rvlenth/lsmeans#2]
Hi,

first of all, thanks for the great package.

I recently wanted to conduct some post-hoc equivalence tests. `lsmeans` provides means to do so but it requires the specification of the equivalence threshold in units of the measurement scale. This can be awkward for some measures commonly used in my field (psychology). In such cases, it may be easier to define the threshold in units of the standardized effect size d<sub>r</sub>, similarly as in [`TOSTER`](https://cran.r-project.org/web/packages/TOSTER/index.html).

I have written a [set of functions](https://gist.github.com/crsh/44a44dee90cba1198288b8c766835809) to facilitate this in `lsmeans` and I was wondering if you would like to include this in the package. I'd be happy to make a pull request including documentation and testing.

I have written methods for `afex` ANOVA; I'm not sure whether these would belong here or should be included in `afex` (cc @singmann).

Cheers

**Comment by rvlenth** [comment]
Frederik,

Thanks for your message. The issue with my incorporating your functions in lsmeans would be that I wouldn’t know how to maintain them. Specifically, what I see in your work are S3 generics for cohens_d_r and mean_difference_r along with methods for different model objects. Potentially in the future, users would want those methods expanded to other models. I would not necessarily know how to provide those methods. And it gets nothing but more complicated when one ventures into mixed models.

It seems to me the ideal approach is for you to develop your own R package that makes those functions available. Then, with both lsmeans and that package attached, you could do the kinds of equivalence tests you want to do simply by putting a call to mean_difference_r, say, as the delta argument in summary, as you show in your demo. As you figure out the right way to obtain effect sizes for other models, you simply update your package. Does that make sense to you?

Best,

Russ

**Comment by rvlenth** [comment]
PS – regarding my suggestion of your own package, I’ll pass on what I’ve learned from writing a package that supports a lot of different models. Since you are providing methods for these models, your need is to export those methods conditionally upon whether they are installed on the user’s system. This is done using code blocks like this in the package’s NAMESPACE file:

if (requireNamespace(afex, quietly = TRUE)) {
    S3method(mean_difference_r, afex_aov)
    S3method(cohen_d_r, afex_aov)
}

Thus, when your package is loaded, the methods for afex_aov objects are registered if afex is installed on the system, and ignored if not.

Maybe that addresses your comment at the end of your message?

Russ

**Comment by crsh** [comment]
Hi Russ,

yes, this makes sense. I had thought about how this could be achieved with mixed models and the related difficulties and I'm currently not sure how to address these issues. I appreciate that this becomes even more difficult if the goal is then to incorporate even more models. Thanks for the advice on the conditional export; I had not come across that method.

Best regards,
Frederik

**Comment by rvlenth** [comment]
I should also have mentioned that the supported namespace should be listed in ‘Suggests’ in the DESCRIPTION file. One might think ‘Enhances’, but every time I’ve tried that I’ve been burned. You can’t include tests that involve packages listed in ‘Enhances’, for example.

You may or may not know I have publications that are fairly critical of standardized effect sizes (in the context of power and sample size). But I would suppose that outside of power/sample size, it makes more sense; and in a lot of mixed-model situations, you’d want to have a choice of which population stratum you wish to relate to. There’s a considerable literature on effect sizes, and the key would be to identify the key contributions (that you agree with) and implement them where you can.

Cheers,

Russ
