### ISSUE TITLE
Subscript out of bounds using clm with scale effect

### ISSUE THREAD

**Issue by troth93** [rvlenth/lsmeans#3]
Hello,

I came across an issue, trying to run post-hocs on a cumulative link model (ordinal package) using lsmeans. My model includes a scale effect:

`clm(Mod~State+SI+FocalAge+FocalSex+SubjectAge+SubjectSex+SubjectSex:SubjectAge, scale=~SI, link="logit", threshold="flexible", data=MyData)`

When I try to run post-hocs on the model including the scale effect, I get the following error:

```
Error in parse(text = x, keep.source = FALSE)[[1L]] : 
  subscript out of bounds
```

When I specify the same model, but exclude the scale effect, it works fine.

Thank you in advance for the support.

**Comment by rvlenth** [comment]
I am able to reproduce the same error with this example:
```
library(ordinal)
library(lsmeans)
wine.clm = clm(rating ~ temp * contact, scale = ~ judge, data = wine)
ref.grid(wine.clm)
## Error in parse(text = x, keep.source = FALSE)[[1L]] : 
##  subscript out of bounds
## Error in ref.grid(wine.clm) : 
##  Perhaps a 'data' or 'params' argument is needed
```
I'm sure I once tested this very example, or something close, so am not sure why it is now broken. Interestingly, it isn't the scale model *per se* that's the problem:
```
ref.grid(wine.clm, mode = "scale")
## 'ref.grid' object with variables:
##     judge = 1, 2, 3, 4, 5, 6, 7, 8, 9
## Transformation: “log”
```
Anyway, I'll comb through things using this example and see what I can find.

**Comment by rvlenth** [comment]
Found a bug. It was actually a bug in some support code that responded less than gracefully when there were no `nominal` effects in the model. Now I have a new bug whereby the factor(s) in the scale model are included in the reference grid for the location model. I don't think that's the way I had it before, so am probing deeper. Anyway, in some sense this new bug is "harmless" in that it just replicates the same predictions at different levels of scale factors. But I'm going to try to get it to stop letting that happen...

**Comment by rvlenth** [comment]
OK, Looking deeper, that's exactly the way I designed it: If you have a scale model, that becomes part of the reference grid for location fixed effects. To get lsmeans, you'll average over those.
```
(rg = ref.grid(wine.clm))
## 'ref.grid' object with variables:
##     temp = cold, warm
##     contact = no, yes
##     judge = 1, 2, 3, 4, 5, 6, 7, 8, 9

lsmeans(rg, "temp")
## NOTE: Results may be misleading due to involvement in interactions
##  temp     lsmean        SE df  asymp.LCL  asymp.UCL
##  cold -1.4659070 0.5136942 NA -2.4727292 -0.4590848
##  warm  0.9563752 0.4122954 NA  0.1482911  1.7644594
## 
## Results are averaged over the levels of: contact, judge
## Confidence level used: 0.95 
```
You may install the latest version from github, or let me know if you want me to package it up for you.

**Comment by troth93** [comment]
Thank you very much! It works fine now
