### ISSUE TITLE
Issue with lmerMod support requiring variables from among the random factors

### ISSUE THREAD

**Issue by rvlenth** [rvlenth/lsmeans#4]
[rvlenth ported this here from an e-mail from Henrik Singmann]

Henrik says...

I have a noticed a weird behavior with lsmeans with random effects variables in merMod objects. I am relatively certain that this behavior (I would call it a bug) has changed at some point and older versions of lsmeans did not show this behavior (although I am not sure when it has changed).

The problem is that lsmeans fails with merMod objects if a variables that only appears in the random effects part of the merMod object (so in principle not relevant for calculating marginal means from fixed effects) is missing from the object in the call[["name"]] slot of the merMod. Passing a data object directly to lsmeans that has this variable does not solve the problem.

An example (somewhat artificial, but afex produces something along those lines):
```
require(lsmeans)
require(lme4)

sleep2 <- sleepstudy
sleep2$Days2 <- sleep2$Days
sleep3 <- sleep2

fm1 <- lmer(Reaction ~ Days + (Days2 | Subject), sleep2)

lsmeans(fm1, "Days")
# Days   lsmean       SE df lower.CL upper.CL
#  4.5 298.5079 9.049936 17 279.4142 317.6016
# 
# Degrees-of-freedom method: satterthwaite 
# Confidence level used: 0.95 

sleep2$Days2 <- NULL
lsmeans(fm1, "Days")
# Error in is.data.frame(data) : object 'sleep2' not found
# Error in ref.grid(object = <S4 object of class "lmerMod">) : 
#   Perhaps a 'data' or 'params' argument is needed

lsmeans(fm1, "Days", data=sleepstudy)
# Error: 'data' not found, and some variables missing from formula environment

lsmeans(fm1, "Days", data=sleep3)
# Error: 'data' not found, and some variables missing from formula environment

fm1@call[["data"]] <- as.name("sleep3")
lsmeans(fm1, "Days")
# Days   lsmean       SE df lower.CL upper.CL
#  4.5 298.5079 9.049936 17 279.4142 317.6016
# 
# Degrees-of-freedom method: satterthwaite 
# Confidence level used: 0.95
```
I could try to track it down if it would help you.

When talking about lsmeans for merMod object, I was wondering if you have thought about providing support for marginal means including the random effects estimates? For example, when requested so, providing a list of merMod objects with one slot with the marginal means per random effect grouping level. I think this would be tremendously helpful. 

Cheers,
Henrik

**Comment by rvlenth** [comment]
Henrik,

First, I was able to replicate the error.

Second, you’re right – it’s a relatively new bug. What has happened is that I changed the default degrees-of-freedom method to Satterthwaite. It is the code in lmerTest that computes the Satterthwaite d.f. that needs the factors in the mixed part of the model. If you do:
```
sleep2$Days2 <- NULL
lsmeans(fm1, "Days", mode = “k”)
##  Days   lsmean       SE df lower.CL upper.CL
##   4.5 298.5079 9.049936 17 279.4142 317.6016
## 
## Degrees-of-freedom method: kenward-roger 
## Confidence level used: 0.95 
```
it works just fine because it then uses the previous default from **pbkrtest**. 

I will consider what, if anything, I can do about this. Maybe issue a warning? Or not? I think it would be fairly uncommon for someone to delete a variable from a dataset.

**Comment by singmann** [comment]
Thanks for looking into this. The problem is kind of easy to stumble upon with `afex::mixed` when using `expand_re=TRUE` (which allows to suppress the correlation among random terms even for factors by transforming the factors into numerical covariates and passing those). See the following example:

```
require(afex)
m1 <- mixed(Reaction ~ Days + (Days || Subject), sleepstudy, expand_re = TRUE)
summary(m1)

lsmeans(m1, "Days")
# Error in eval(predvars, data, env) : object 're1.Days' not found

lsmeans(m1, "Days", mode="k")
# Days   lsmean       SE    df lower.CL upper.CL
#  4.5 298.5079 8.878989 24.96 280.2198  316.796
# 
# Degrees-of-freedom method: kenward-roger 
# Confidence level used: 0.95 

lsmeans(m1, "Days", mode="a")
# Days   lsmean       SE df asymp.LCL asymp.UCL
#  4.5 298.5079 8.878989 NA  281.1054  315.9104
# 
# Degrees-of-freedom method: asymptotic 
# Confidence level used: 0.95 
```

I am not suggesting you implement specific provisions for that (I will just add a corresponding warning to the `mixed` documentation), but just wanted to document it here.
