### ISSUE TITLE
would this package work with vcov coming from the sandwich package?

### ISSUE THREAD

**Issue by randomgambit** [rvlenth/lsmeans#7]
Hello!

Thanks for this amazing package. I am wondering if it would work when one uses robust or HAC standard errors coming from the `sandwich` R package?

Thanks!

**Comment by rvlenth** [comment]
The answer is yes; any compatible matrix or function may be supplied via the `vcov.` argument. Here's a silly example:

```
> require("lsmeans")
> fiber.lm <- lm(strength ~ diameter + machine, data=fiber)
> fakev <- 2*vcov(fiber.lm)

> summary(ref.grid(fiber.lm))
 diameter machine prediction        SE df
 24.13333 A         40.38241 0.7236252 11
 24.13333 B         41.41922 0.7444169 11
 24.13333 C         38.79836 0.7878785 11

> summary(ref.grid(fiber.lm, vcov. = fakev))
 diameter machine prediction       SE df
 24.13333 A         40.38241 1.023361 11
 24.13333 B         41.41922 1.052765 11
 24.13333 C         38.79836 1.114228 11

> summary(ref.grid(fiber.lm, vcov. = function(x) 3*vcov(x)))
 diameter machine prediction       SE df
 24.13333 A         40.38241 1.253356 11
 24.13333 B         41.41922 1.289368 11
 24.13333 C         38.79836 1.364646 11
```

The first output is using the vcov obtained from the object. The second uses a matrix with twice those values; and the third uses a function that triples the values.

I'm realizing that this is not well (at all?) documented. I will make an effort to improve the documentation to make this more obvious.



```

**Comment by randomgambit** [comment]
@rvlenth thanks and sorry for my late reply. I was actually referring to the computation of robust confidence intervals. I would like to plot the usual regression line, along with Huber-White confidence intervals (or any other vcov). Can I tweak your code to do so?
Thanks!!

**Comment by rvlenth** [comment]
@randomgambit Yes, if I understand your question correctly. You can do something like this:
```
df1 <- summary(lsmeans(...))
df2 <- summary(lsmeans(..., vcov. = my.vcov))
```
Now `df1` and `df2` are data frames with the results with the two covariance estimators. Between them, you have all the results you need, and can do further standard data-frame merges or other manipulations to organize the results for plotting purposes.

**Comment by rvlenth** [comment]
@randomgambit - Is this **lsmeans** issue resolved to your satisfaction?

**Comment by randomgambit** [comment]
@rvlenth yes, thank you!
